version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=tarefasdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: tarefasdb
      MYSQL_USER: "root"

    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./front
    image: docker-front-app
    ports:
      - "3001:3001"
    volumes:
      - ./front:/app

  portainer:
    image: portainer/portainer-ce:latest
    container_name: z3smartdigital-portainer
    hostname: z3smartdigital-portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data_container:/data
    ports:
      - "9000:9000"
      - "9443:9443"

volumes:
  mysql_data:
  portainer_data_container:
